"use client";

import { useEffect, useState } from "react";

/**
 * Custom React Hook to reactively determine if Hidden Features (Paper Trading & News Graph Overlay) are activated.
 */
export function useHiddenFeatures(): boolean {
  const [enabled, setEnabled] = useState<boolean>(false);

  useEffect(() => {
    const checkFlags = async () => {
      // 1. Check URL query string e.g. ?hidden_features=true or false
      if (typeof window !== "undefined") {
        const params = new URLSearchParams(window.location.search);
        if (params.has("hidden_features")) {
          const val = params.get("hidden_features") === "true";
          localStorage.setItem("enable_hidden_features", val ? "true" : "false");
          setEnabled(val);
          return;
        }

        // 2. Check localStorage saved by launcher
        const localVal = localStorage.getItem("enable_hidden_features");
        if (localVal !== null) {
          setEnabled(localVal === "true");
          return;
        }
      }

      // 3. Fetch runtime feature-flags.json generated by launcher
      try {
        const res = await fetch("/feature-flags.json");
        const data = await res.json();
        if (data && typeof data.enableHiddenFeatures === "boolean") {
          setEnabled(data.enableHiddenFeatures);
          return;
        }
      } catch (err) {
        // Ignore fetch errors
      }

      // 4. Fallback to process.env
      setEnabled(process.env.NEXT_PUBLIC_ENABLE_HIDDEN_FEATURES === "true");
    };

    checkFlags();
  }, []);

  return enabled;
}
